services:
  - type: web
    name: project-sos-pricing-engine
    env: static
    branch: main
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
